version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: 13289812
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
