version: '3.8'

services:
  redis:
    image: "redis:7.4.0"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: 13289812
  app:
    container_name: "app"
    build: .
    image: "github-search-app:latest"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
    name: "github-search-app-redis-data"
    driver: local
