apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-search-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-search-app
  template:
    metadata:
      labels:
        app: github-search-app
    spec:
      containers:
        - name: github-search-app
          image: github-search-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: redis-secret
          volumeMounts:
            - name: app-config-volume
              mountPath: /config/application.properties
              subPath: application.properties
      volumes:
        - name: app-config-volume
          configMap:
            name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: github-search-app
spec:
  selector:
    app: github-search-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer