apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: dGVzdERCCg==  # base64 закодоване "testDB"
  POSTGRES_USER: YWRtaW4=  # base64 закодоване "admin"
  POSTGRES_PASSWORD: MTMyODk4MTI=  # base64 закодоване "13289812"