name: Java CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Set up JDK 21
      - name: Set up JDK 21
        id: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-21-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-21-

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      # Restore cached Maven dependencies from the setup job
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-21-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-21-

      # Run Maven build
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  checkstyle:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      # Restore cached Maven dependencies from the setup job
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-21-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-21-

      # Run Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:check

      # Upload Checkstyle report as an artifact
      - name: Upload Checkstyle Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report-${{ github.run_id }}
          path: target/checkstyle-result.xml

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      # Restore cached Maven dependencies from the setup job
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-21-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-21-

      # Run tests
      - name: Run Tests with Maven
        run: mvn test

      # Upload test results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ github.run_id }}
          path: target/surefire-reports/*.xml