name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [maven-build, checkstyle]
        java-version: [21]
        os: [ubuntu-latest]

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ matrix.java-version }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.java-version }}-

      # Set up JDK 21
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      # Run Maven build
      - name: Build with Maven
        if: matrix.task == 'maven-build'
        run: mvn --batch-mode --update-snapshots verify

      # Run Checkstyle
      - name: Run Checkstyle
        if: matrix.task == 'checkstyle'
        run: mvn checkstyle:check

      # Upload Checkstyle report as an artifact
      - name: Upload Checkstyle Report
        if: always() && matrix.task == 'checkstyle'
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Set up JDK 21
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ matrix.java-version }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ matrix.java-version }}-

      # Run tests
      - name: Run Tests with Maven
        run: mvn test

      # Upload test results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/*.xml